import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header/Header'
import Relogio from '@/components/Relogio/Relogio';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {

  const data = new Date()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          
          min-h-screen flex flex-col items-center justify-start p-20 gap-2 
          `} 
      >
        <Header />
        <main className="bg-blue-200 p-5 rounded-2xl min-h-[70vh] 
                          w-full md:w-5/6 lg:w-4/5 xl:w-5/5">
          {children}
        </main>
        <footer className="w-full mt-6 flex items-center justify-between text-sm text-gray-700">
          <div>DIW, {data.getFullYear()}</div>
          <div>
            <Relogio />
          </div>
        </footer>
      </body>
    </html>
  );
}
